/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f4f5",
        "on-primary-fixed-variant": "#2435b4",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#d6dced",
        "on-tertiary-fixed-variant": "#404754",
        "inverse-primary": "#bcc2ff",
        "inverse-on-surface": "#f0f1f2",
        "outline-variant": "#c6c5d6",
        "surface-variant": "#e1e3e4",
        "tertiary": "#424956",
        "secondary-fixed": "#dce2f7",
        "tertiary-container": "#5a616f",
        "surface-dim": "#d9dadb",
        "on-secondary": "#ffffff",
        "on-primary-container": "#d8daff",
        "on-background": "#191c1d",
        "tertiary-fixed-dim": "#c0c7d6",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "tertiary-fixed": "#dce2f3",
        "outline": "#757685",
        "background": "#f8f9fa",
        "on-surface-variant": "#454654",
        "surface-bright": "#f8f9fa",
        "surface": "#f8f9fa",
        "on-secondary-fixed-variant": "#404758",
        "on-secondary-fixed": "#141b2b",
        "on-tertiary-fixed": "#151c27",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#c0c6db",
        "inverse-surface": "#2e3132",
        "surface-container-high": "#e7e8e9",
        "on-surface": "#191c1d",
        "on-primary-fixed": "#000b63",
        "on-secondary-container": "#5c6274",
        "primary": "#4353cf",
        "surface-container": "#edeeef",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "primary-container": "#4353cf",
        "primary-fixed-dim": "#bcc2ff",
        "primary-fixed": "#dfe0ff",
        "on-primary": "#ffffff",
        "surface-tint": "#4050cc",
        "secondary-container": "#d9dff5",
        "secondary": "#575e70"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "2rem",
        "gutter": "1.5rem",
        "margin-desktop": "2.5rem",
        "sm": "1rem",
        "xs": "0.5rem",
        "md": "1.5rem",
        "base": "4px",
        "margin-mobile": "1rem",
        "xl": "3rem",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "label-caps": ["Geist"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "button": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"]
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["20px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "button": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
